name: network_image_progres
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  logger: ^1.1.0
  lottie: ^1.2.2
  url_launcher: ^6.0.20
  connectivity: ^3.0.6
  connectivity_plus: ^2.2.1
  fluttertoast: ^8.0.8
  path_provider: ^2.0.9
  path: ^1.8.0
  permission_handler: ^9.1.0
  percent_indicator: ^4.0.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
   - assets/images/
   - assets/anims/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
